import { ThemeProvider } from '@/components/theme-provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import { UserProvider } from '@auth0/nextjs-auth0/client';

import { ApolloWrapper } from './AppWrapper';
import { Toaster } from '@/components/ui/toaster';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                {/* <UserProvider> */}
                    <ApolloWrapper>
                        <ThemeProvider
                            attribute='class'
                            defaultTheme='system'
                            enableSystem>
                            {children}
                            <Toaster />
                        </ThemeProvider>
                    </ApolloWrapper>
                {/* </UserProvider> */}
            </body>
        </html>
    );
}
